//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MlaWebApi.EFModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class Friend
    {
        public long userId { get; set; }
        public Nullable<long> FriendUserId { get; set; }
        public Nullable<long> GroupId { get; set; }
        public long friendId { get; set; }
    
        public virtual register register { get; set; }
    }
}
