//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MlaWebApi.EFModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class Group_key
    {
        public long user_id { get; set; }
        public decimal group_key_id { get; set; }
        public string group_key1 { get; set; }
        public Nullable<long> group_id { get; set; }
        public Nullable<bool> status { get; set; }
        public Nullable<decimal> version { get; set; }
    
        public virtual Group_table Group_table { get; set; }
    }
}
