//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MlaWebApi.EFModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class Post
    {
        public string post1 { get; set; }
        public string postType { get; set; }
        public long groupid { get; set; }
        public decimal postid { get; set; }
        public Nullable<decimal> version_no { get; set; }
        public Nullable<System.DateTime> timestamp { get; set; }
        public string digitalsignature { get; set; }
        public string owner { get; set; }
        public string session_key { get; set; }
        public Nullable<long> userId { get; set; }
    
        public virtual Group_table Group_table { get; set; }
    }
}
